import { Component, OnInit, inject, ChangeDetectorRef } from '@angular/core';
import { CommonModule } from '@angular/common';
import { FormsModule } from '@angular/forms';
import { RouterModule } from '@angular/router';
import { ProjectService } from '../../../services/project.service';
import { SiteExpense } from '../../../models/project.model';
import { OfficeService } from '../../../services/office.service';
import { AuthService } from '../../../services/auth.service';
import { MasterListService } from '../../../services/master-list.service';
import jsPDF from 'jspdf';
import autoTable from 'jspdf-autotable';
import * as XLSX from 'xlsx';

@Component({
  selector: 'app-warehouse-expenses',
  standalone: true,
  imports: [CommonModule, FormsModule, RouterModule],
  templateUrl: './warehouse-expenses.component.html',
  styleUrls: ['./warehouse-expenses.component.css']
})
export class WarehouseExpensesComponent implements OnInit {
  private projectService = inject(ProjectService);
  private officeService = inject(OfficeService);
  private authService = inject(AuthService);
  private masterListService = inject(MasterListService);
  private cdr = inject(ChangeDetectorRef);

  expenses: SiteExpense[] = [];
  loading = false;
  searchQuery = '';

  // Pagination
  currentPage = 1;
  pageSize = 15;

  // --- EXCEL UPLOAD MODAL STATE ---
  isExcelModalOpen = false;
  excelRawRows: any[] = [];
  excelHeaders: string[] = [];
  excelMapping = {
    date: '',
    referenceNo: '',
    invoiceNo: '',
    purpose: '',
    amount: '',
    vendor: '',
    paidBy: '',
    generatedBy: '',
    paymentThrough: '',
    remarks: ''
  };

  alertMessage: { text: string; type: 'success' | 'danger' } | null = null;

  onExcelFileSelected(event: any): void {
    const file = event.target.files?.[0];
    if (!file) return;

    const reader = new FileReader();
    reader.onload = (e: any) => {
      try {
        const data = new Uint8Array(e.target.result);
        const workbook = XLSX.read(data, { type: 'array' });
        const firstSheetName = workbook.SheetNames[0];
        const worksheet = workbook.Sheets[firstSheetName];
        const jsonData: any[] = XLSX.utils.sheet_to_json(worksheet, { defval: '' });

        if (jsonData.length === 0) {
          this.showAlert('Selected Excel file is empty', 'danger');
          return;
        }

        this.excelRawRows = jsonData;
        this.excelHeaders = Object.keys(jsonData[0]);

        const findHeader = (keywords: string[]) => {
          return this.excelHeaders.find(h => {
            const lower = h.toLowerCase().trim();
            return keywords.some(k => lower === k || lower.includes(k));
          }) || '';
        };

        this.excelMapping = {
          date: findHeader(['date', 'created', 'day', 'time', 'awarded']),
          referenceNo: findHeader(['po / wo no', 'po/wo no', 'po / wo', 'po/wo', 'po no', 'wo no', 'po #', 'wo #', 'ref', 'order no', 'po', 'wo']),
          invoiceNo: findHeader(['invoice no', 'invoice #', 'inv no', 'inv #', 'tax invoice', 'bill no', 'bill #']),
          purpose: findHeader(['bom material', 'material', 'purpose', 'category', 'item', 'description']),
          amount: findHeader(['expense amount', 'amount', 'cost', 'expense', 'price']),
          vendor: findHeader(['vendor name', 'vendor', 'supplier', 'seller', 'party', 'shop', 'company', 'paid to', 'payee']),
          paidBy: findHeader(['paid by', 'engineer', 'order by', 'handler']),
          generatedBy: findHeader(['generated by', 'created by', 'entered by', 'user']),
          paymentThrough: findHeader(['through', 'mode', 'channel', 'payment mode']),
          remarks: findHeader(['remarks / description', 'remarks', 'description', 'notes', 'comments'])
        };

        this.isExcelModalOpen = true;
        this.cdr.markForCheck();
      } catch (err: any) {
        this.showAlert('Failed to read Excel file: ' + err.message, 'danger');
      }
      event.target.value = '';
    };
    reader.readAsArrayBuffer(file);
  }

  closeExcelModal(): void {
    this.isExcelModalOpen = false;
    this.excelRawRows = [];
    this.excelHeaders = [];
  }

  confirmImportExcel(): void {
    if (this.excelRawRows.length === 0) return;

    let importedCount = 0;
    for (const row of this.excelRawRows) {
      const purpose = this.excelMapping.purpose ? String(row[this.excelMapping.purpose] || '').trim() : 'Warehouse Expense';
      const amount = this.excelMapping.amount ? parseFloat(row[this.excelMapping.amount]) || 0 : 0;
      let vendor = this.excelMapping.vendor ? String(row[this.excelMapping.vendor] || '').trim() : '';

      const generatedBy = this.excelMapping.generatedBy ? String(row[this.excelMapping.generatedBy] || '').trim() : '';
      const rawPaidBy = this.excelMapping.paidBy ? String(row[this.excelMapping.paidBy] || '').trim() : '';
      const rawSource = this.excelMapping.paymentThrough ? String(row[this.excelMapping.paymentThrough] || '').trim() : '';

      let refNo = this.excelMapping.referenceNo ? String(row[this.excelMapping.referenceNo] || '').trim() : '';
      if (['P.O', 'W.O', 'Petty Cash', 'Accounts', 'WAREHOUSE', 'Not Submitted', 'Submitted', '-'].includes(refNo)) {
        refNo = '';
      }

      // Determine Source (paymentThrough): MUST strictly be P.O, W.O, Petty Cash, Gatepass, or Accounts
      let paymentThrough = '';
      if (refNo) {
        if (refNo.toUpperCase().includes('WO-') || refNo.toUpperCase().includes('W.O')) {
          paymentThrough = 'W.O';
        } else {
          paymentThrough = 'P.O';
        }
      }

      if (!paymentThrough) {
        const checkStr = `${rawSource} ${rawPaidBy}`.toLowerCase();
        if (checkStr.includes('gatepass') || checkStr.includes('gate pass')) {
          paymentThrough = 'Gatepass';
        } else if (checkStr.includes('account') || checkStr.includes('bank')) {
          paymentThrough = 'Accounts';
        } else if (checkStr.includes('w.o') || checkStr.includes('work order')) {
          paymentThrough = 'W.O';
        } else if (checkStr.includes('p.o') || checkStr.includes('purchase order')) {
          paymentThrough = 'P.O';
        } else {
          paymentThrough = 'Petty Cash';
        }
      }

      // Determine Paid By (staff / engineer name)
      let paidBy = generatedBy;
      if (!paidBy && rawPaidBy && !['P.O', 'W.O', 'Petty Cash', 'Accounts', 'Gatepass'].includes(rawPaidBy)) {
        paidBy = rawPaidBy;
      }
      if (!paidBy) {
        paidBy = 'OFFICE';
      }

      let remarks = this.excelMapping.remarks ? String(row[this.excelMapping.remarks] || '').trim() : '';
      const rawDate = this.excelMapping.date ? row[this.excelMapping.date] : null;
      const expenseDate = rawDate ? this.normalizeToIsoDate(rawDate) : new Date().toISOString().split('T')[0];

      let invNo = this.excelMapping.invoiceNo ? String(row[this.excelMapping.invoiceNo] || '').trim() : '';
      if (['Not Submitted', 'Submitted', 'P.O', 'W.O', 'Petty Cash', 'WAREHOUSE', '-'].includes(invNo)) {
        invNo = '';
      }

      // Fallback: If vendor is empty, check if remarks holds the party/vendor name, or fallback for Petty Cash
      if (!vendor) {
        if (remarks) {
          vendor = remarks;
        } else if (paymentThrough === 'Petty Cash' || rawPaidBy === 'Petty Cash' || paidBy === 'Petty Cash') {
          vendor = 'Petty Cash / Local Vendor';
        }
      }

      const billVoucherCol = this.excelHeaders.find(h => h.toLowerCase().includes('bill voucher') || h.toLowerCase().includes('voucher'));
      const billVoucher = billVoucherCol ? String(row[billVoucherCol] || '').trim() : 'Submitted';

      if (amount > 0 || purpose) {
        const newExpense: Partial<SiteExpense> = {
          siteId: 'WAREHOUSE',
          clientName: 'Warehouse : Sathlokhar H.O',
          purpose: purpose,
          amount: amount,
          vendorName: vendor,
          paidBy: paidBy,
          paymentThrough: paymentThrough,
          referenceNo: refNo,
          invoiceNo: invNo,
          expenseDate: expenseDate,
          remarks: remarks,
          billVoucher: billVoucher || 'Submitted'
        };
        this.projectService.createExpense(newExpense).subscribe();
        importedCount++;
      }
    }

    this.showAlert(`Successfully imported ${importedCount} warehouse expenses from Excel`, 'success');
    this.closeExcelModal();
    setTimeout(() => this.loadExpenses(), 800);
  }

  showAlert(text: string, type: 'success' | 'danger'): void {
    this.alertMessage = { text, type };
    setTimeout(() => this.alertMessage = null, 4000);
  }

  normalizeToIsoDate(val: any): string {
    if (!val) return new Date().toISOString().substring(0, 10);
    if (val instanceof Date) {
      if (isNaN(val.getTime())) return new Date().toISOString().substring(0, 10);
      const yyyy = val.getFullYear();
      const mm = String(val.getMonth() + 1).padStart(2, '0');
      const dd = String(val.getDate()).padStart(2, '0');
      return `${yyyy}-${mm}-${dd}`;
    }

    if (typeof val === 'number' || (typeof val === 'string' && /^\d{5}(\.\d+)?$/.test(val.trim()))) {
      const num = typeof val === 'number' ? val : parseFloat(val.trim());
      if (num > 10000 && num < 100000) {
        const jsDate = new Date(Math.round((num - 25569) * 86400 * 1000));
        if (!isNaN(jsDate.getTime())) {
          const yyyy = jsDate.getUTCFullYear();
          const mm = String(jsDate.getUTCMonth() + 1).padStart(2, '0');
          const dd = String(jsDate.getUTCDate()).padStart(2, '0');
          return `${yyyy}-${mm}-${dd}`;
        }
      }
    }

    const str = String(val).trim().replace(/[T\s].*$/, '');
    if (!str) return new Date().toISOString().substring(0, 10);

    if (/^\d{4}-\d{2}-\d{2}$/.test(str)) {
      return str;
    }

    if (str.includes('-') || str.includes('/') || str.includes('.')) {
      const isSlash = str.includes('/');
      const parts = str.split(/[-/.]/).map(p => p.trim());

      if (parts.length === 3) {
        let p0 = parseInt(parts[0], 10);
        let p1 = parseInt(parts[1], 10);
        let p2 = parseInt(parts[2], 10);

        if (!isNaN(p0) && !isNaN(p1) && !isNaN(p2)) {
          let year = p2;
          let month = 0;
          let day = 0;

          if (p0 > 1000) {
            year = p0;
            if (p1 > 12) { month = p2; day = p1; }
            else { month = p1; day = p2; }
          } else {
            if (year < 100) year += 2000;

            if (isSlash) {
              // Slash format default: MM/DD/YYYY (US format e.g. 7/31/2026, 4/13/2026)
              if (p0 > 12 && p1 <= 12) {
                day = p0;
                month = p1;
              } else {
                month = p0;
                day = p1;
              }
            } else {
              // Dash / Dot format default: DD-MM-YYYY (Indian format e.g. 04-10-2026, 04-09-2026)
              if (p1 > 12 && p0 <= 12) {
                month = p0;
                day = p1;
              } else {
                day = p0;
                month = p1;
              }
            }
          }

          if (year >= 1900 && year <= 2100 && month >= 1 && month <= 12 && day >= 1 && day <= 31) {
            const yStr = String(year);
            const mStr = String(month).padStart(2, '0');
            const dStr = String(day).padStart(2, '0');
            return `${yStr}-${mStr}-${dStr}`;
          }
        }
      }
    }

    const dObj = new Date(str);
    if (!isNaN(dObj.getTime())) {
      const yyyy = dObj.getFullYear();
      const mm = String(dObj.getMonth() + 1).padStart(2, '0');
      const dd = String(dObj.getDate()).padStart(2, '0');
      return `${yyyy}-${mm}-${dd}`;
    }

    return new Date().toISOString().substring(0, 10);
  }

  // Add / Edit Modal
  isModalOpen = false;
  isEditMode = false;
  editingId: number | null = null;
  isLegacyPurpose = false;

  formData = {
    dateInput: '', // dd-mm-yyyy
    paymentThrough: 'P.O',
    purpose: 'Inverters - 3kW Ongrid',
    selectedBomGroup: 'Inverters',
    selectedBomSpec: '3kW Ongrid',
    customBomSpec: '',
    paidBy: 'OFFICE',
    vendor: '',
    remarks: '',
    billVoucher: 'Submitted',
    referenceNo: '',
    invoiceNo: '',
    amount: null as number | null
  };

  paymentThroughOptions = ['P.O', 'W.O', 'Petty Cash', 'Gatepass', 'Accounts', '(Blanks)'];

  // BOM Material Master Groups & Specifications
  bomMaterialGroups: { group: string; specifications: string[] }[] = [
    {
      group: 'Panels',
      specifications: ['540W Mono PERC', '550W Mono PERC', '580W TOPCon', '335W Polycrystalline', '340W Polycrystalline']
    },
    {
      group: 'Inverters',
      specifications: ['3kW Ongrid', '5kW Ongrid', '10kW Ongrid', '15kW Ongrid', '20kW Ongrid', '5kW Hybrid', '10kW Hybrid']
    },
    {
      group: 'Cables',
      specifications: ['AC Cable - 4Sqmm', 'AC Cable - 6Sqmm', 'AC Cable - 10Sqmm', 'AC Cable - 16Sqmm', 'AC Cable - 25Sqmm', 'DC Cable - XLPO 4Sqmm', 'DC Cable - XLPO 6Sqmm', 'DC Cable - 10Sqmm']
    },
    {
      group: 'Transportation & Logistics',
      specifications: ['Freight & Site Logistics', 'Local Tempo / Mini Truck', 'Site Shifting & Handling', 'Crane / Unloading Services']
    },
    {
      group: 'Consumables & Miscellaneous',
      specifications: ['General Consumables', 'DB Boxes', 'Cable Tray Materials', 'Rental Tools', 'Tools Asset', 'Walkway / Hand Rails', 'General Stock']
    }
  ];

  paidByOptions: string[] = ['OFFICE'];
  vendorOptions: string[] = [];

  // Delete modal
  isDeleteModalOpen = false;
  expenseToDelete: SiteExpense | null = null;

  // Alert toast
  toastMessage = '';
  toastType: 'success' | 'danger' | 'info' = 'success';

  ngOnInit(): void {
    this.formData.dateInput = this.getTodayDisplayDate();
    this.loadExpenses();
    this.loadVendorsFromOffice();
    this.loadEmployeesFromOffice();
    this.loadBomMaterialsFromService();
  }

  loadBomMaterialsFromService(): void {
    this.masterListService.getBomMaterials().subscribe({
      next: (res) => {
        if (res.success && res.grouped) {
          Object.keys(res.grouped).forEach(grpName => {
            const items = res.grouped[grpName];
            const specs = items.map((it: any) => it.specification || it.categoryType).filter(Boolean);
            const existing = this.bomMaterialGroups.find(g => g.group.toLowerCase().trim() === grpName.toLowerCase().trim());
            if (existing) {
              existing.specifications = Array.from(new Set([...existing.specifications, ...specs]));
            } else {
              this.bomMaterialGroups.push({ group: grpName, specifications: specs.length > 0 ? specs : ['General'] });
            }
          });
          this.cdr.markForCheck();
        }
      },
      error: () => {}
    });
  }

  getAvailableSpecs(groupName: string): string[] {
    const grp = this.bomMaterialGroups.find(g => g.group.toLowerCase().trim() === (groupName || '').toLowerCase().trim());
    return grp ? grp.specifications : ['General'];
  }

  onBomGroupChange(): void {
    this.isLegacyPurpose = false;
    const specs = this.getAvailableSpecs(this.formData.selectedBomGroup);
    this.formData.selectedBomSpec = specs[0] || 'General';
    this.formData.customBomSpec = '';
    this.updatePurposeFromBom();
  }

  onBomSpecChange(): void {
    this.isLegacyPurpose = false;
    this.updatePurposeFromBom();
  }

  updatePurposeFromBom(): void {
    if (this.formData.selectedBomSpec === 'Custom') {
      this.formData.purpose = this.formData.customBomSpec?.trim()
        ? `${this.formData.selectedBomGroup} - ${this.formData.customBomSpec.trim()}`
        : this.formData.selectedBomGroup;
    } else if (this.formData.selectedBomSpec) {
      this.formData.purpose = `${this.formData.selectedBomGroup} - ${this.formData.selectedBomSpec}`;
    } else {
      this.formData.purpose = this.formData.selectedBomGroup;
    }
  }

  canAdd(): boolean {
    return this.authService.canAdd('expense-ledger') || this.authService.isAdmin();
  }

  canEdit(): boolean {
    return this.authService.canEdit('expense-ledger') || this.authService.isAdmin();
  }

  canDelete(): boolean {
    return this.authService.canDelete('expense-ledger') || this.authService.isAdmin();
  }

  isAdmin(): boolean {
    return this.authService.isAdmin();
  }

  loadVendorsFromOffice(): void {
    this.officeService.getVendors().subscribe({
      next: (res) => {
        if (res.success && res.data?.length > 0) {
          const names = res.data.map(v => v.vendorName).filter(Boolean);
          this.vendorOptions = Array.from(new Set(names));
          this.cdr.markForCheck();
        }
      }
    });
  }

  loadEmployeesFromOffice(): void {
    this.officeService.getEmployees().subscribe({
      next: (res) => {
        if (res.success && res.data?.length > 0) {
          const names = res.data.map(e => e.name).filter(Boolean);
          this.paidByOptions = Array.from(new Set(['OFFICE', ...names]));
          this.cdr.markForCheck();
        }
      }
    });
  }

  loadExpenses(): void {
    this.loading = true;
    this.projectService.getExpenses({ siteId: 'WAREHOUSE' }).subscribe({
      next: (res) => {
        if (res.success && res.data) {
          this.expenses = res.data;
        }
        this.loading = false;
        this.cdr.markForCheck();
      },
      error: (err) => {
        console.error('Error fetching warehouse expenses:', err);
        this.loading = false;
        this.cdr.markForCheck();
      }
    });
  }

  get filteredExpenses(): SiteExpense[] {
    let list = this.expenses;
    if (this.searchQuery) {
      const q = this.searchQuery.toLowerCase().trim();
      list = list.filter(e =>
        (e.purpose || '').toLowerCase().includes(q) ||
        (e.paidBy || '').toLowerCase().includes(q) ||
        (e.vendorName || '').toLowerCase().includes(q) ||
        (e.remarks || '').toLowerCase().includes(q) ||
        (e.paymentThrough || '').toLowerCase().includes(q) ||
        (e.expenseDate || '').toLowerCase().includes(q) ||
        (e.referenceNo || '').toLowerCase().includes(q) ||
        (e.invoiceNo || '').toLowerCase().includes(q)
      );
    }
    return list;
  }

  get paginatedExpenses(): SiteExpense[] {
    const start = (this.currentPage - 1) * this.pageSize;
    return this.filteredExpenses.slice(start, start + this.pageSize);
  }

  get totalPages(): number {
    return Math.ceil(this.filteredExpenses.length / this.pageSize) || 1;
  }

  changePage(page: number): void {
    if (page >= 1 && page <= this.totalPages) {
      this.currentPage = page;
    }
  }

  get totalExpenseAmount(): number {
    return this.expenses.reduce((sum, e) => sum + (Number(e.amount) || 0), 0);
  }

  // --- MODAL ACTIONS ---
  openAddModal(): void {
    this.isEditMode = false;
    this.isLegacyPurpose = false;
    this.editingId = null;
    this.formData = {
      dateInput: this.getTodayDisplayDate(),
      paymentThrough: 'P.O',
      purpose: 'Inverters - 3kW Ongrid',
      selectedBomGroup: 'Inverters',
      selectedBomSpec: '3kW Ongrid',
      customBomSpec: '',
      paidBy: 'OFFICE',
      vendor: '',
      remarks: 'Material stock received in Central Warehouse',
      billVoucher: 'Submitted',
      referenceNo: '',
      invoiceNo: '',
      amount: null
    };
    this.isModalOpen = true;
  }

  openEditModal(e: SiteExpense): void {
    this.isEditMode = true;
    this.editingId = e.id || null;

    const rawPurpose = e.purpose || 'Consumables';
    let matchedGroup = '';
    let matchedSpec = '';

    for (const g of this.bomMaterialGroups) {
      if (rawPurpose.toLowerCase().includes(g.group.toLowerCase())) {
        matchedGroup = g.group;
        const foundSpec = g.specifications.find(s => rawPurpose.toLowerCase().includes(s.toLowerCase()));
        if (foundSpec) matchedSpec = foundSpec;
        break;
      }
    }

    if (!matchedGroup) {
      // Legacy purpose that doesn't match new BOM schema - PRESERVE INTACT
      this.isLegacyPurpose = true;
      matchedGroup = rawPurpose;
      matchedSpec = 'Custom';
    } else {
      this.isLegacyPurpose = false;
    }

    // Clean invoiceNo: if it contains PO/WO strings, leave invoiceNo empty for manual entry
    const cleanInvNo = (e.invoiceNo && !e.invoiceNo.startsWith('SOLAR/') && !e.invoiceNo.includes('/PO-') && !e.invoiceNo.includes('/WO-')) 
      ? e.invoiceNo 
      : '';

    this.formData = {
      dateInput: e.formattedDate || this.toDisplayDate(e.expenseDate),
      paymentThrough: e.paymentThrough || 'P.O',
      purpose: rawPurpose, // 100% preserves existing database data
      selectedBomGroup: matchedGroup || 'Inverters',
      selectedBomSpec: matchedSpec || (this.getAvailableSpecs(matchedGroup)[0] || 'General'),
      customBomSpec: this.isLegacyPurpose ? rawPurpose : '',
      paidBy: e.paidBy || 'OFFICE',
      vendor: e.vendorName || '',
      remarks: e.remarks || '',
      billVoucher: e.billVoucher || 'Submitted',
      referenceNo: e.referenceNo || '',
      invoiceNo: cleanInvNo,
      amount: Number(e.amount) || null
    };
    this.isModalOpen = true;
  }

  getSource(e: SiteExpense): string {
    const ref = (e.referenceNo || '').trim();
    const isPoWoRef = ref && !['P.O', 'W.O', 'Petty Cash', 'Accounts', 'WAREHOUSE', 'Not Submitted', 'Submitted', '-'].includes(ref) && !ref.toUpperCase().startsWith('PC-');
    if (isPoWoRef) {
      return ref.toUpperCase().includes('WO-') || ref.toUpperCase().includes('W.O') ? 'W.O' : 'P.O';
    }
    if (e.paymentThrough === 'Gatepass' || e.paymentThrough === 'GatePass') return 'Gatepass';
    if (e.paymentThrough === 'Accounts') return 'Accounts';
    if (e.paymentThrough === 'W.O') return 'W.O';
    if (e.paymentThrough === 'P.O') return 'P.O';
    return 'Petty Cash';
  }

  clearAllWarehouseExpenses(): void {
    if (confirm('Are you sure you want to clear ALL warehouse expense records? This will delete all current records so you can upload a clean Excel file.')) {
      this.projectService.deleteExpensesBySite('WAREHOUSE').subscribe({
        next: (res) => {
          this.showAlert('All warehouse expense records cleared successfully.', 'success');
          this.loadExpenses();
        },
        error: (err) => {
          this.showAlert('Failed to clear records: ' + (err?.message || 'Error'), 'danger');
        }
      });
    }
  }

  closeModal(): void {
    this.isModalOpen = false;
    this.editingId = null;
    this.isLegacyPurpose = false;
  }

  submitExpense(): void {
    if (!this.formData.amount || this.formData.amount <= 0) {
      this.showToast('Please enter a valid positive expense amount', 'danger');
      return;
    }

    const isoDate = this.toIsoDate(this.formData.dateInput);
    const mop = this.deriveMoPFromDate(this.formData.dateInput);

    let finalPurpose = this.formData.purpose;
    if (!this.isLegacyPurpose && this.formData.selectedBomGroup) {
      if (this.formData.selectedBomSpec === 'Custom' && this.formData.customBomSpec?.trim()) {
        finalPurpose = `${this.formData.selectedBomGroup} - ${this.formData.customBomSpec.trim()}`;
      } else if (this.formData.selectedBomSpec && this.formData.selectedBomSpec !== 'Custom') {
        finalPurpose = `${this.formData.selectedBomGroup} - ${this.formData.selectedBomSpec}`;
      } else {
        finalPurpose = this.formData.selectedBomGroup;
      }
    }

    const payload: Partial<SiteExpense> = {
      siteId: 'WAREHOUSE',
      clientName: 'Warehouse : Sathlokhar H.O',
      clientSiteName: 'Warehouse : Sathlokhar H.O',
      expenseDate: isoDate,
      mop,
      amount: Number(this.formData.amount),
      paymentThrough: this.formData.paymentThrough,
      purpose: finalPurpose,
      category: this.formData.selectedBomGroup || 'Warehouse',
      paidBy: this.formData.paidBy,
      vendorName: this.formData.vendor || '',
      remarks: this.formData.remarks || '',
      billVoucher: this.formData.billVoucher || 'Submitted',
      referenceNo: this.formData.referenceNo ? this.formData.referenceNo.trim() : '',
      invoiceNo: this.formData.invoiceNo ? this.formData.invoiceNo.trim() : ''
    };

    if (this.isEditMode && this.editingId) {
      this.projectService.updateExpense(this.editingId, payload).subscribe({
        next: (res) => {
          if (res.success) {
            this.showToast('Warehouse expense updated successfully!', 'success');
            this.closeModal();
            this.loadExpenses();
          }
        },
        error: () => this.showToast('Failed to update expense', 'danger')
      });
    } else {
      this.projectService.createExpense(payload).subscribe({
        next: (res) => {
          if (res.success) {
            this.showToast('Warehouse expense recorded successfully!', 'success');
            this.closeModal();
            this.loadExpenses();
          }
        },
        error: () => this.showToast('Failed to record expense', 'danger')
      });
    }
  }

  // --- DELETE MODAL ---
  confirmDelete(e: SiteExpense): void {
    this.expenseToDelete = e;
    this.isDeleteModalOpen = true;
  }

  closeDeleteModal(): void {
    this.isDeleteModalOpen = false;
    this.expenseToDelete = null;
  }

  executeDelete(): void {
    if (!this.expenseToDelete?.id) return;
    const id = this.expenseToDelete.id;

    this.projectService.deleteExpense(id).subscribe({
      next: (res) => {
        if (res.success) {
          this.showToast('Expense record deleted successfully', 'success');
          this.closeDeleteModal();
          this.loadExpenses();
        }
      },
      error: () => this.showToast('Failed to delete expense', 'danger')
    });
  }

  // --- PDF EXPORT ---
  exportPdf(): void {
    const doc = new jsPDF({ orientation: 'landscape', unit: 'mm', format: 'a4' });
    const primaryColor: [number, number, number] = [15, 23, 42];
    const accentColor: [number, number, number] = [37, 99, 235]; // Primary blue

    doc.setFont('helvetica', 'bold');
    doc.setFontSize(16);
    doc.setTextColor(...primaryColor);
    doc.text('SOLAR SATHLOKHAR - WAREHOUSE EXPENSES LEDGER', 14, 18);

    doc.setFont('helvetica', 'normal');
    doc.setFontSize(9);
    doc.setTextColor(100, 116, 139);
    doc.text(`Facility: Sathlokhar H.O Central Store | Total Incurred: Rs. ${this.totalExpenseAmount.toLocaleString('en-IN')}`, 14, 25);

    const tableRows = this.filteredExpenses.map((e, index) => [
      index + 1,
      this.toDisplayDate(e.expenseDate),
      e.referenceNo || '—',
      e.invoiceNo || '—',
      e.purpose || 'Consumables',
      e.vendorName || '—',
      e.paymentThrough || 'P.O',
      e.paidBy || 'OFFICE',
      `Rs. ${(Number(e.amount) || 0).toLocaleString('en-IN', { minimumFractionDigits: 2, maximumFractionDigits: 2 })}`
    ]);

    autoTable(doc, {
      startY: 30,
      head: [['#', 'Date', 'PO/WO No.', 'Invoice No', 'BOM Material / Purpose', 'Vendor', 'Payment', 'Paid By', 'Amount']],
      body: tableRows,
      theme: 'grid',
      headStyles: {
        fillColor: accentColor,
        textColor: [255, 255, 255],
        fontStyle: 'bold',
        fontSize: 8.5
      },
      bodyStyles: {
        fontSize: 8,
        textColor: [30, 41, 59]
      },
      columnStyles: {
        0: { cellWidth: 10, halign: 'center' },
        1: { cellWidth: 22, halign: 'center' },
        2: { cellWidth: 32 },
        3: { cellWidth: 25 },
        4: { cellWidth: 42 },
        5: { cellWidth: 32 },
        6: { cellWidth: 20 },
        7: { cellWidth: 22 },
        8: { cellWidth: 25, halign: 'right', fontStyle: 'bold', textColor: [37, 99, 235] }
      },
      margin: { left: 14, right: 14 }
    });

    doc.save(`Warehouse_Expenses_Ledger_${new Date().toISOString().slice(0, 10)}.pdf`);
    this.showToast('PDF downloaded successfully!', 'info');
  }

  exportToExcel(): void {
    if (!this.filteredExpenses || this.filteredExpenses.length === 0) {
      this.showToast('No records to export to Excel', 'danger');
      return;
    }
    const headers = ['#', 'Date', 'Ref No', 'Invoice No', 'Purpose / Description', 'Vendor Name', 'Payment Through', 'Paid By', 'Amount (INR)'];
    const rows = this.filteredExpenses.map((e, index) => [
      index + 1,
      `"${this.toDisplayDate(e.expenseDate)}"`,
      `"${e.referenceNo || ''}"`,
      `"${e.invoiceNo || ''}"`,
      `"${(e.purpose || '').replace(/"/g, '""')}"`,
      `"${(e.vendorName || '').replace(/"/g, '""')}"`,
      `"${e.paymentThrough || ''}"`,
      `"${e.paidBy || ''}"`,
      e.amount || 0
    ]);
    const csvContent = 'data:text/csv;charset=utf-8,' + [headers.join(','), ...rows.map(r => r.join(','))].join('\n');
    const encodedUri = encodeURI(csvContent);
    const link = document.createElement('a');
    link.setAttribute('href', encodedUri);
    link.setAttribute('download', `Warehouse_Expenses_${new Date().toISOString().slice(0, 10)}.csv`);
    document.body.appendChild(link);
    link.click();
    document.body.removeChild(link);
    this.showToast('Excel/CSV downloaded successfully!', 'success');
  }

  exportBothPdfAndExcel(): void {
    this.exportPdf();
    setTimeout(() => {
      this.exportToExcel();
    }, 450);
  }

  toDisplayDate(isoStr: string | undefined | null): string {
    if (!isoStr) return '';
    const iso = this.normalizeToIsoDate(isoStr);
    if (!iso || iso.length < 10) return String(isoStr).trim();
    const parts = iso.substring(0, 10).split('-');
    if (parts.length === 3 && parts[0].length === 4) {
      const yyyy = parts[0];
      const mm = parts[1].padStart(2, '0');
      const dd = parts[2].padStart(2, '0');
      return `${dd}-${mm}-${yyyy}`;
    }
    return String(isoStr).trim();
  }

  toIsoDate(inputStr: string | undefined): string {
    if (!inputStr) return new Date().toISOString().slice(0, 10);
    return this.normalizeToIsoDate(inputStr);
  }

  getTodayDisplayDate(): string {
    const today = new Date();
    const dd = String(today.getDate()).padStart(2, '0');
    const mm = String(today.getMonth() + 1).padStart(2, '0');
    const yyyy = today.getFullYear();
    return `${dd}-${mm}-${yyyy}`;
  }

  deriveMoPFromDate(dateStr: string): string {
    const iso = this.toIsoDate(dateStr);
    const d = new Date(iso);
    if (isNaN(d.getTime())) return '';
    const months = ['Jan', 'Feb', 'Mar', 'Apr', 'May', 'Jun', 'Jul', 'Aug', 'Sep', 'Oct', 'Nov', 'Dec'];
    return `${months[d.getMonth()]}-${String(d.getFullYear()).slice(-2)}`;
  }

  onDatePickerChange(isoDate: string): void {
    if (isoDate) {
      this.formData.dateInput = this.toDisplayDate(isoDate);
      this.cdr.markForCheck();
      this.cdr.detectChanges();
    }
  }

  openDatePicker(picker: HTMLInputElement): void {
    if (!picker) return;
    try {
      if (typeof picker.showPicker === 'function') {
        picker.showPicker();
      } else {
        picker.focus();
        picker.click();
      }
    } catch {
      try {
        picker.focus();
        picker.click();
      } catch (err) {
        console.error('Failed to open date picker:', err);
      }
    }
  }

  showToast(msg: string, type: 'success' | 'danger' | 'info'): void {
    this.toastMessage = msg;
    this.toastType = type;
    this.cdr.markForCheck();
    setTimeout(() => {
      this.toastMessage = '';
      this.cdr.markForCheck();
    }, 3500);
  }
}
